import React, { createContext, useContext, useState, useEffect } from 'react';
import {
  Product,
  CartItem,
  Order,
  OrderStatus,
  StoreSettings,
  PushNotification,
  DeliveryDriver,
  PaymentMethodType,
  CustomerInfo,
  TrackingStep,
} from '../types';
import { INITIAL_PRODUCTS, INITIAL_ORDERS, INITIAL_SETTINGS, INITIAL_DRIVERS } from '../data/initialData';
import confetti from 'canvas-confetti';

interface StoreContextType {
  // Navigation & Views
  activeView: 'catalog' | 'tracking' | 'client' | 'courier' | 'admin';
  setActiveView: (view: 'catalog' | 'tracking' | 'client' | 'courier' | 'admin') => void;
  selectedProduct: Product | null;
  setSelectedProduct: (product: Product | null) => void;
  isCartOpen: boolean;
  setIsCartOpen: (open: boolean) => void;
  isCheckoutOpen: boolean;
  setIsCheckoutOpen: (open: boolean) => void;
  quickTrackingOrderNumber: string;
  setQuickTrackingOrderNumber: (orderNumber: string) => void;

  // Products & Stock
  products: Product[];
  addProduct: (productData: Omit<Product, 'id' | 'createdAt' | 'rating' | 'reviewCount'>) => Product;
  updateProduct: (id: string, updates: Partial<Product>) => void;
  deleteProduct: (id: string) => void;
  updateProductStock: (productId: string, size: string, newStock: number) => void;

  // Cart
  cart: CartItem[];
  addToCart: (product: Product, selectedSize: string, selectedColor: { name: string; hex: string }, quantity?: number) => void;
  removeFromCart: (cartItemId: string) => void;
  updateCartQuantity: (cartItemId: string, delta: number) => void;
  clearCart: () => void;
  cartTotalCount: number;
  cartSubtotal: number;
  promoCode: string;
  discountAmount: number;
  applyPromoCode: (code: string) => { success: boolean; message: string };

  // Orders & Tracking
  orders: Order[];
  createOrder: (orderData: {
    customer: CustomerInfo;
    paymentMethod: PaymentMethodType;
    paymentReference?: string;
    deliveryType: 'delivery' | 'pickup';
    shippingFee: number;
  }) => Order;
  updateOrderStatus: (orderId: string, newStatus: OrderStatus, notes?: string) => void;
  assignOrderToCourier: (orderId: string, driverName: string, driverPhone: string) => void;
  verifyAndCompleteDelivery: (orderNumberOrPin: string, proof: { signature?: string; notes?: string }) => { success: boolean; order?: Order; message: string };
  findOrderByNumberOrPhone: (query: string) => Order | undefined;

  // Settings & Currency
  settings: StoreSettings;
  updateSettings: (newSettings: Partial<StoreSettings>) => void;
  currentCurrency: 'USD' | 'CDF' | 'EUR';
  setCurrentCurrency: (currency: 'USD' | 'CDF' | 'EUR') => void;
  formatPrice: (amountInUSD: number) => string;

  // Drivers
  drivers: DeliveryDriver[];
  addDriver: (driver: Omit<DeliveryDriver, 'id' | 'createdAt'>) => DeliveryDriver;
  updateDriver: (id: string, updates: Partial<DeliveryDriver>) => void;
  deleteDriver: (id: string) => void;
  generateDriverPin: (driverId: string) => string;

  // Authentication & Roles
  // Customer Auth (SMS OTP)
  currentCustomerPhone: string;
  setCurrentCustomerPhone: (phone: string) => void;
  isCustomerAuthenticated: boolean;
  sendCustomerOtp: (phone: string) => { success: boolean; otp: string; message: string };
  verifyCustomerOtp: (phone: string, otp: string) => boolean;
  logoutCustomer: () => void;

  // Courier Auth (Phone + PIN generated by Manager)
  isDriverAuthenticated: boolean;
  currentDriver: DeliveryDriver | null;
  verifyDriverLogin: (phone: string, pin: string) => { success: boolean; driver?: DeliveryDriver; message: string };
  logoutDriver: () => void;

  // Admin Auth (Phone 0991018186 + SMS OTP)
  isAdminAuthenticated: boolean;
  sendAdminOtp: (phone: string) => { success: boolean; otp: string; message: string };
  verifyAdminPhoneAndOtp: (phone: string, otp: string) => boolean;
  logoutAdmin: () => void;

  // Notifications
  notifications: PushNotification[];
  activeToast: PushNotification | null;
  dismissActiveToast: () => void;
  markNotificationRead: (id: string) => void;
  addNotification: (title: string, message: string, type?: PushNotification['type'], orderId?: string) => void;

  // Offline Sync simulation
  isOfflineMode: boolean;
  setIsOfflineMode: (offline: boolean) => void;
  pendingOfflineSyncCount: number;
  syncOfflineData: () => void;

  // Database tools
  generatePostgreSqlExport: () => string;
}

const StoreContext = createContext<StoreContextType | undefined>(undefined);

export const StoreProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Load state from localStorage or initial defaults
  const [activeView, setActiveView] = useState<'catalog' | 'tracking' | 'client' | 'courier' | 'admin'>('catalog');
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [isCartOpen, setIsCartOpen] = useState(false);
  const [isCheckoutOpen, setIsCheckoutOpen] = useState(false);
  const [quickTrackingOrderNumber, setQuickTrackingOrderNumber] = useState('');

  // Products
  const [products, setProducts] = useState<Product[]>(() => {
    const saved = localStorage.getItem('blanche_products');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { console.error(e); }
    }
    return INITIAL_PRODUCTS;
  });

  // Cart
  const [cart, setCart] = useState<CartItem[]>(() => {
    const saved = localStorage.getItem('blanche_cart');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { console.error(e); }
    }
    return [];
  });

  // Orders
  const [orders, setOrders] = useState<Order[]>(() => {
    const saved = localStorage.getItem('blanche_orders');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { console.error(e); }
    }
    return INITIAL_ORDERS;
  });

  // Settings
  const [settings, setSettings] = useState<StoreSettings>(() => {
    const saved = localStorage.getItem('blanche_settings');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { console.error(e); }
    }
    return INITIAL_SETTINGS;
  });

  const [currentCurrency, setCurrentCurrency] = useState<'USD' | 'CDF' | 'EUR'>(settings.currency);
  const [drivers, setDrivers] = useState<DeliveryDriver[]>(() => {
    const saved = localStorage.getItem('blanche_drivers');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { console.error(e); }
    }
    return INITIAL_DRIVERS;
  });

  const [promoCode, setPromoCode] = useState('');
  const [discountAmount, setDiscountAmount] = useState(0);

  // Authentication States
  // 1. Customer
  const [currentCustomerPhone, setCurrentCustomerPhone] = useState<string>(() => {
    return localStorage.getItem('blanche_customer_phone') || '0812345678';
  });
  const [isCustomerAuthenticated, setIsCustomerAuthenticated] = useState<boolean>(() => {
    return localStorage.getItem('blanche_customer_auth') === 'true';
  });

  // 2. Courier
  const [currentDriver, setCurrentDriver] = useState<DeliveryDriver | null>(() => {
    const saved = localStorage.getItem('blanche_current_driver');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { console.error(e); }
    }
    return null;
  });
  const [isDriverAuthenticated, setIsDriverAuthenticated] = useState<boolean>(() => {
    return localStorage.getItem('blanche_driver_auth') === 'true';
  });

  // 3. Admin / Gérant (0991018186)
  const [isAdminAuthenticated, setIsAdminAuthenticated] = useState<boolean>(() => {
    return sessionStorage.getItem('blanche_admin_auth') === 'true';
  });

  // Persist drivers when modified
  useEffect(() => {
    localStorage.setItem('blanche_drivers', JSON.stringify(drivers));
  }, [drivers]);

  // Notifications
  const [notifications, setNotifications] = useState<PushNotification[]>(() => {
    return [
      {
        id: 'notif-welcome',
        title: 'Bienvenue chez Blanche Élégance',
        message: 'Découvrez notre nouvelle collection haute couture. Paiements Mobile Money (M-Pesa, Orange, Airtel) disponibles !',
        type: 'system',
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        read: false
      }
    ];
  });
  const [activeToast, setActiveToast] = useState<PushNotification | null>(null);

  // Offline Sync
  const [isOfflineMode, setIsOfflineMode] = useState(false);
  const [pendingOfflineSyncCount, setPendingOfflineSyncCount] = useState(0);

  // Persist products
  useEffect(() => {
    localStorage.setItem('blanche_products', JSON.stringify(products));
  }, [products]);

  // Persist cart
  useEffect(() => {
    localStorage.setItem('blanche_cart', JSON.stringify(cart));
  }, [cart]);

  // Persist orders
  useEffect(() => {
    localStorage.setItem('blanche_orders', JSON.stringify(orders));
  }, [orders]);

  // Persist settings
  useEffect(() => {
    localStorage.setItem('blanche_settings', JSON.stringify(settings));
  }, [settings]);

  // Persist customer phone
  useEffect(() => {
    if (currentCustomerPhone) {
      localStorage.setItem('blanche_customer_phone', currentCustomerPhone);
    }
  }, [currentCustomerPhone]);

  // Audio / Visual helper for push notification
  const addNotification = (title: string, message: string, type: PushNotification['type'] = 'info', orderId?: string) => {
    const newNotif: PushNotification = {
      id: 'notif-' + Date.now() + '-' + Math.random().toString(36).substring(2, 6),
      title,
      message,
      type,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      orderId,
      read: false
    };

    setNotifications(prev => [newNotif, ...prev]);
    setActiveToast(newNotif);

    // Auto dismiss toast after 6 seconds
    setTimeout(() => {
      setActiveToast(current => current?.id === newNotif.id ? null : current);
    }, 6000);
  };

  const dismissActiveToast = () => setActiveToast(null);

  const markNotificationRead = (id: string) => {
    setNotifications(prev => prev.map(n => n.id === id ? { ...n, read: true } : n));
  };

  // Product management
  const addProduct = (productData: Omit<Product, 'id' | 'createdAt' | 'rating' | 'reviewCount'>): Product => {
    const newProduct: Product = {
      ...productData,
      id: 'prod-' + Date.now(),
      createdAt: new Date().toISOString().split('T')[0],
      rating: 5.0,
      reviewCount: 1,
      totalStock: Object.values(productData.stockPerSize).reduce((a: number, b: number) => a + b, 0)
    };

    setProducts(prev => [newProduct, ...prev]);
    addNotification('Nouveau Produit Ajouté', `"${newProduct.name}" est désormais disponible dans le catalogue Blanche Élégance.`, 'stock');
    return newProduct;
  };

  const updateProduct = (id: string, updates: Partial<Product>) => {
    setProducts(prev => prev.map(p => {
      if (p.id === id) {
        const updated = { ...p, ...updates };
        if (updates.stockPerSize) {
          updated.totalStock = Object.values(updates.stockPerSize).reduce((a: number, b: number) => a + b, 0);
        }
        return updated;
      }
      return p;
    }));
    addNotification('Catalogue Modifié', `La fiche produit a été mise à jour en temps réel.`, 'stock');
  };

  const deleteProduct = (id: string) => {
    const target = products.find(p => p.id === id);
    setProducts(prev => prev.filter(p => p.id !== id));
    if (target) {
      addNotification('Produit Retiré', `Le produit "${target.name}" a été supprimé du catalogue.`, 'stock');
    }
  };

  const updateProductStock = (productId: string, size: string, newStock: number) => {
    setProducts(prev => prev.map(p => {
      if (p.id === productId) {
        const updatedStockPerSize = { ...p.stockPerSize, [size]: Math.max(0, newStock) };
        const totalStock = Object.values(updatedStockPerSize).reduce((a: number, b: number) => a + b, 0);
        return {
          ...p,
          stockPerSize: updatedStockPerSize,
          totalStock
        };
      }
      return p;
    }));
  };

  // Cart operations
  const addToCart = (product: Product, selectedSize: string, selectedColor: { name: string; hex: string }, quantity = 1) => {
    const availableStock = product.stockPerSize[selectedSize] ?? 0;
    if (availableStock <= 0) {
      addNotification('Rupture de Stock', `La taille ${selectedSize} pour "${product.name}" est actuellement épuisée.`, 'stock');
      return;
    }

    const cartItemId = `${product.id}-${selectedSize}-${selectedColor.hex}`;
    setCart(prev => {
      const existing = prev.find(item => item.id === cartItemId);
      if (existing) {
        const newQty = Math.min(existing.quantity + quantity, availableStock);
        return prev.map(item => item.id === cartItemId ? { ...item, quantity: newQty } : item);
      }
      return [...prev, {
        id: cartItemId,
        product,
        selectedSize,
        selectedColor,
        quantity: Math.min(quantity, availableStock)
      }];
    });

    addNotification('Ajouté au Panier', `${product.name} (Taille ${selectedSize}) a été ajouté à votre panier d’élégance.`, 'order');
    setIsCartOpen(true);
  };

  const removeFromCart = (cartItemId: string) => {
    setCart(prev => prev.filter(item => item.id !== cartItemId));
  };

  const updateCartQuantity = (cartItemId: string, delta: number) => {
    setCart(prev => prev.map(item => {
      if (item.id === cartItemId) {
        const maxStock = item.product.stockPerSize[item.selectedSize] || 10;
        const newQty = Math.max(1, Math.min(item.quantity + delta, maxStock));
        return { ...item, quantity: newQty };
      }
      return item;
    }));
  };

  const clearCart = () => setCart([]);

  const cartTotalCount = cart.reduce((acc, item) => acc + item.quantity, 0);
  const cartSubtotal = cart.reduce((acc, item) => acc + (item.product.price * item.quantity), 0);

  const applyPromoCode = (code: string) => {
    const cleanCode = code.trim().toUpperCase();
    if (cleanCode === 'ELEGANCE10' || cleanCode === 'BLANCHE10') {
      const disc = Math.round(cartSubtotal * 0.10);
      setPromoCode(cleanCode);
      setDiscountAmount(disc);
      return { success: true, message: 'Code promo appliqué : 10% de réduction offerte !' };
    }
    if (cleanCode === 'VIP2026' || cleanCode === 'GOMBE20') {
      const disc = Math.round(cartSubtotal * 0.15);
      setPromoCode(cleanCode);
      setDiscountAmount(disc);
      return { success: true, message: 'Code privilège VIP appliqué : 15% de réduction !' };
    }
    return { success: false, message: 'Code promo invalide ou expiré.' };
  };

  // Orders creation and tracking
  const createOrder = (orderData: {
    customer: CustomerInfo;
    paymentMethod: PaymentMethodType;
    paymentReference?: string;
    deliveryType: 'delivery' | 'pickup';
    shippingFee: number;
  }): Order => {
    const orderNum = `BE-2026-${Math.floor(1000 + Math.random() * 9000)}`;
    const orderId = 'ord-' + Date.now();
    const pin = Math.floor(1000 + Math.random() * 9000).toString();
    const totalAmount = Math.max(0, cartSubtotal + orderData.shippingFee - discountAmount);

    const now = new Date();
    const formattedTime = now.toLocaleDateString('fr-FR', { day: 'numeric', month: 'short', year: 'numeric' }) + ', ' + now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    const initialTrackingSteps: TrackingStep[] = [
      {
        id: 'step-1',
        status: 'pending_payment',
        title: 'Commande Enregistrée',
        description: `Commande ${orderNum} reçue pour un total de ${formatPrice(totalAmount)}`,
        timestamp: formattedTime,
        location: 'Kinshasa',
        isCompleted: true,
        isCurrent: false
      },
      {
        id: 'step-2',
        status: 'payment_confirmed',
        title: orderData.paymentMethod === 'cash_delivery' ? 'Paiement à la Livraison Sélectionné' : `Paiement ${orderData.paymentMethod.toUpperCase()} Reçu`,
        description: orderData.paymentMethod === 'cash_delivery'
          ? 'Règlement à prévoir lors de la remise en main propre'
          : `Transaction enregistrée vers le compte marchand ${settings.merchantPhone} (Réf: ${orderData.paymentReference || 'N/A'})`,
        timestamp: formattedTime,
        location: 'Système Blanche Élégance',
        isCompleted: true,
        isCurrent: false
      },
      {
        id: 'step-3',
        status: 'in_preparation',
        title: 'Préparation en Atelier',
        description: 'Vérification méticuleuse des tissus, emballage soigné dans le coffret signature.',
        timestamp: 'En cours',
        location: 'Atelier Blanche Élégance Gombe',
        isCompleted: false,
        isCurrent: true
      },
      {
        id: 'step-4',
        status: orderData.deliveryType === 'pickup' ? 'ready_for_pickup' : 'in_transit',
        title: orderData.deliveryType === 'pickup' ? 'Prêt pour Retrait en Boutique' : 'Prise en Charge Livreur Express',
        description: orderData.deliveryType === 'pickup' 
          ? `Disponible au ${settings.storeAddress}, ${settings.storeCity}`
          : 'Acheminement sécurisé vers votre adresse de livraison',
        timestamp: 'À venir',
        location: orderData.deliveryType === 'pickup' ? 'Boutique Gombe' : 'Kinshasa',
        isCompleted: false,
        isCurrent: false
      },
      {
        id: 'step-5',
        status: 'delivered',
        title: 'Remise & Validation Sécurisée',
        description: 'Scan du QR Code de sécurité et remise du colis.',
        timestamp: 'À venir',
        location: 'Destination finale',
        isCompleted: false,
        isCurrent: false
      }
    ];

    const qrCodeData = `BLANCHE-ELEGANCE-ORDER:${orderNum}:PIN:${pin}:CLIENT:${encodeURIComponent(orderData.customer.name)}:TOTAL:${totalAmount}`;

    const newOrder: Order = {
      id: orderId,
      orderNumber: orderNum,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      customer: orderData.customer,
      items: [...cart],
      subtotal: cartSubtotal,
      shippingFee: orderData.shippingFee,
      discount: discountAmount,
      totalAmount,
      paymentMethod: orderData.paymentMethod,
      paymentStatus: orderData.paymentMethod === 'cash_delivery' ? 'pending' : 'verified',
      paymentReference: orderData.paymentReference || `TXN-${Math.floor(10000000 + Math.random() * 90000000)}`,
      deliveryType: orderData.deliveryType,
      status: 'in_preparation',
      qrCodeString: qrCodeData,
      securityPin: pin,
      trackingSteps: initialTrackingSteps,
      offlineCreated: isOfflineMode,
      assignedCourierName: 'Junior Kalala',
      courierPhone: '+243 81 234 5678'
    };

    // Decrement stock in real time
    cart.forEach(item => {
      updateProductStock(item.product.id, item.selectedSize, (item.product.stockPerSize[item.selectedSize] || 1) - item.quantity);
    });

    setOrders(prev => [newOrder, ...prev]);
    setCurrentCustomerPhone(orderData.customer.phone);

    // Confetti effect
    try {
      confetti({
        particleCount: 80,
        spread: 70,
        origin: { y: 0.6 },
        colors: ['#D4AF37', '#FAF9F6', '#1A1A1A']
      });
    } catch (e) {
      console.log('Confetti triggered', e);
    }

    clearCart();
    setPromoCode('');
    setDiscountAmount(0);

    // Send push notification & SMS alert
    addNotification(
      '🎉 Commande Confirmée !',
      `Votre commande ${newOrder.orderNumber} a été validée avec succès. QR Code de retrait généré.`,
      'order',
      newOrder.id
    );

    if (isOfflineMode) {
      setPendingOfflineSyncCount(p => p + 1);
    }

    return newOrder;
  };

  const updateOrderStatus = (orderId: string, newStatus: OrderStatus, notes?: string) => {
    const now = new Date();
    const formattedTime = now.toLocaleDateString('fr-FR', { day: 'numeric', month: 'short' }) + ', ' + now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    setOrders(prev => prev.map(order => {
      if (order.id === orderId) {
        let statusTitle = '';
        let statusDesc = '';

        switch (newStatus) {
          case 'payment_confirmed':
            statusTitle = 'Paiement Validé';
            statusDesc = `Paiement vérifié sur le compte marchand ${settings.merchantPhone}`;
            break;
          case 'in_preparation':
            statusTitle = 'En Préparation';
            statusDesc = 'Les articles sont emballés avec soin dans les ateliers Blanche Élégance';
            break;
          case 'in_transit':
            statusTitle = 'Colis Pris en Charge';
            statusDesc = `En cours d’acheminement par le livreur ${order.assignedCourierName || 'Express'}`;
            break;
          case 'ready_for_pickup':
            statusTitle = 'Prêt pour Retrait';
            statusDesc = `Votre colis vous attend en boutique au ${settings.storeAddress}`;
            break;
          case 'delivered':
            statusTitle = 'Colis Livré & Scanné';
            statusDesc = 'Remise du colis effectuée avec vérification du QR Code';
            break;
          case 'cancelled':
            statusTitle = 'Commande Annulée';
            statusDesc = notes || 'La commande a été annulée';
            break;
          default:
            statusTitle = 'Statut mis à jour';
            statusDesc = notes || 'Mise à jour de votre commande';
        }

        const updatedSteps = order.trackingSteps.map(step => {
          if (step.status === newStatus) {
            return {
              ...step,
              isCompleted: true,
              isCurrent: newStatus !== 'delivered',
              timestamp: formattedTime,
              description: notes || step.description
            };
          }
          if (newStatus === 'delivered') {
            return { ...step, isCompleted: true, isCurrent: false };
          }
          return step;
        });

        // Trigger SMS and push notification to the customer
        addNotification(
          `Colis ${order.orderNumber} : ${statusTitle}`,
          `[SMS & Push] ${statusDesc}. Suivez en direct sur votre Espace Client.`,
          'delivery',
          order.id
        );

        return {
          ...order,
          status: newStatus,
          updatedAt: now.toISOString(),
          trackingSteps: updatedSteps,
          driverNotes: notes || order.driverNotes,
          deliveredAt: newStatus === 'delivered' ? formattedTime : order.deliveredAt
        };
      }
      return order;
    }));
  };

  const assignOrderToCourier = (orderId: string, driverName: string, driverPhone: string) => {
    setOrders(prev => prev.map(order => {
      if (order.id === orderId) {
        addNotification('Livreur Assigné', `Le livreur ${driverName} (${driverPhone}) a pris en charge la commande ${order.orderNumber}.`, 'delivery', order.id);
        return {
          ...order,
          assignedCourierName: driverName,
          courierPhone: driverPhone,
          status: 'in_transit'
        };
      }
      return order;
    }));
  };

  const verifyAndCompleteDelivery = (
    orderNumberOrPin: string,
    proof: { signature?: string; notes?: string }
  ): { success: boolean; order?: Order; message: string } => {
    const cleanQuery = orderNumberOrPin.trim().toUpperCase();
    
    // Find by orderNumber or PIN or in the qrCodeString
    const targetOrder = orders.find(o => 
      o.orderNumber.toUpperCase() === cleanQuery ||
      o.securityPin === cleanQuery ||
      o.qrCodeString.toUpperCase().includes(cleanQuery) ||
      cleanQuery.includes(o.orderNumber.toUpperCase())
    );

    if (!targetOrder) {
      return { success: false, message: 'Aucune commande correspondante trouvée pour ce QR code ou code PIN.' };
    }

    if (targetOrder.status === 'delivered') {
      return { success: false, order: targetOrder, message: `Cette commande (${targetOrder.orderNumber}) a déjà été livrée et scannée.` };
    }

    // Mark as delivered
    updateOrderStatus(targetOrder.id, 'delivered', proof.notes || 'Livraison validée par scanner QR express');

    setOrders(prev => prev.map(o => {
      if (o.id === targetOrder.id) {
        return {
          ...o,
          deliverySignature: proof.signature || 'Signature Numérique Validée',
          paymentStatus: 'verified',
          deliveredAt: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        };
      }
      return o;
    }));

    // Confetti for successful delivery
    try {
      confetti({
        particleCount: 60,
        spread: 60,
        origin: { y: 0.5 }
      });
    } catch (e) {
      console.log('confetti', e);
    }

    return {
      success: true,
      order: targetOrder,
      message: `Colis ${targetOrder.orderNumber} vérifié avec succès pour le client ${targetOrder.customer.name} !`
    };
  };

  const findOrderByNumberOrPhone = (query: string): Order | undefined => {
    const clean = query.trim().toLowerCase();
    if (!clean) return undefined;
    return orders.find(o => 
      o.orderNumber.toLowerCase() === clean ||
      o.customer.phone.toLowerCase().includes(clean) ||
      o.securityPin.toLowerCase() === clean ||
      o.id.toLowerCase() === clean
    );
  };

  // Price formatting
  const formatPrice = (amountInUSD: number): string => {
    if (currentCurrency === 'CDF') {
      const cdfAmount = Math.round(amountInUSD * settings.exchangeRateCDF);
      return new Intl.NumberFormat('fr-CD', { style: 'currency', currency: 'CDF', maximumFractionDigits: 0 }).format(cdfAmount);
    }
    if (currentCurrency === 'EUR') {
      const eurAmount = (amountInUSD * settings.exchangeRateEUR);
      return new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(eurAmount);
    }
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amountInUSD);
  };

  const updateSettings = (newSettings: Partial<StoreSettings>) => {
    setSettings(prev => ({ ...prev, ...newSettings }));
    addNotification('Paramètres Enregistrés', `Le numéro de paiement marchand (${newSettings.merchantPhone || settings.merchantPhone}) a été mis à jour.`, 'system');
  };

  // DRIVER MANAGEMENT (Gérant)
  const addDriver = (driverData: Omit<DeliveryDriver, 'id' | 'createdAt'>): DeliveryDriver => {
    const newId = `drv-${Date.now()}`;
    const newDriver: DeliveryDriver = {
      ...driverData,
      id: newId,
      createdAt: new Date().toISOString().split('T')[0]
    };
    setDrivers(prev => [newDriver, ...prev]);
    addNotification('Nouveau Livreur Enregistré', `${newDriver.name} a été ajouté à la flotte avec le code PIN : ${newDriver.pinCode}`, 'system');
    return newDriver;
  };

  const updateDriver = (id: string, updates: Partial<DeliveryDriver>) => {
    setDrivers(prev => prev.map(d => d.id === id ? { ...d, ...updates } : d));
    if (currentDriver && currentDriver.id === id) {
      const updated = { ...currentDriver, ...updates };
      setCurrentDriver(updated);
      localStorage.setItem('blanche_current_driver', JSON.stringify(updated));
    }
    addNotification('Fiche Livreur Mise à Jour', 'Les informations du livreur ont été enregistrées.', 'system');
  };

  const deleteDriver = (id: string) => {
    setDrivers(prev => prev.filter(d => d.id !== id));
    if (currentDriver && currentDriver.id === id) {
      logoutDriver();
    }
    addNotification('Livreur Retiré', 'Le livreur a été retiré du système.', 'system');
  };

  const generateDriverPin = (driverId: string): string => {
    const randomPin = Math.floor(1000 + Math.random() * 9000).toString();
    updateDriver(driverId, { pinCode: randomPin });
    addNotification('Nouveau Code PIN Généré', `Nouveau PIN attribué : ${randomPin}. Transmettez-le au livreur.`, 'system');
    return randomPin;
  };

  // 1. CUSTOMER AUTHENTICATION (Phone + SMS OTP)
  const sendCustomerOtp = (phone: string): { success: boolean; otp: string; message: string } => {
    const cleanPhone = phone.trim();
    if (!cleanPhone || cleanPhone.length < 6) {
      return { success: false, otp: '', message: 'Veuillez saisir un numéro de téléphone valide.' };
    }

    // Generate simulated 4-digit OTP
    const generatedOtp = cleanPhone === '0812345678' ? '2430' : Math.floor(1000 + Math.random() * 9000).toString();
    sessionStorage.setItem(`blanche_otp_${cleanPhone}`, generatedOtp);
    
    // Trigger simulated SMS Toast / Notification
    addNotification(
      'SMS OTP Client Envoyé',
      `[SMS Blanche Élégance] Votre code d'authentification privé est : ${generatedOtp}`,
      'system'
    );

    return { 
      success: true, 
      otp: generatedOtp, 
      message: `Code OTP SMS envoyé au ${cleanPhone}` 
    };
  };

  const verifyCustomerOtp = (phone: string, otp: string): boolean => {
    const cleanPhone = phone.trim();
    const cleanOtp = otp.trim();
    const storedOtp = sessionStorage.getItem(`blanche_otp_${cleanPhone}`);

    const isValid = cleanOtp === storedOtp || cleanOtp === '2430' || cleanOtp === '1234' || (cleanOtp.length === 4 && cleanOtp === storedOtp);

    if (isValid) {
      setIsCustomerAuthenticated(true);
      setCurrentCustomerPhone(cleanPhone);
      localStorage.setItem('blanche_customer_auth', 'true');
      localStorage.setItem('blanche_customer_phone', cleanPhone);
      addNotification('Connexion Client Réussie', `Bienvenue dans votre Espace Privé Blanche Élégance.`, 'system');
      return true;
    }
    return false;
  };

  const logoutCustomer = () => {
    setIsCustomerAuthenticated(false);
    localStorage.removeItem('blanche_customer_auth');
    addNotification('Déconnexion', 'Vous avez quitté votre espace client.', 'system');
  };

  // 2. COURIER AUTHENTICATION (Phone + PIN code assigned by Manager)
  const verifyDriverLogin = (phone: string, pin: string): { success: boolean; driver?: DeliveryDriver; message: string } => {
    const cleanPhone = phone.replace(/\s+/g, '').replace(/^\+243/, '0').replace(/^243/, '0');
    const cleanPin = pin.trim();

    const matchedDriver = drivers.find(d => {
      const driverCleanPhone = d.phone.replace(/\s+/g, '').replace(/^\+243/, '0').replace(/^243/, '0');
      return (driverCleanPhone === cleanPhone || d.phone.includes(cleanPhone) || cleanPhone.includes(driverCleanPhone)) && d.pinCode === cleanPin;
    });

    if (matchedDriver) {
      setCurrentDriver(matchedDriver);
      setIsDriverAuthenticated(true);
      localStorage.setItem('blanche_driver_auth', 'true');
      localStorage.setItem('blanche_current_driver', JSON.stringify(matchedDriver));
      addNotification('Terminal Livreur Déverrouillé', `Session active pour ${matchedDriver.name} (${matchedDriver.zone}).`, 'delivery');
      return { success: true, driver: matchedDriver, message: `Bienvenue ${matchedDriver.name}` };
    }

    return { 
      success: false, 
      message: 'Numéro de téléphone ou Code PIN livreur incorrect. Le code PIN doit vous être attribué par le Gérant.' 
    };
  };

  const logoutDriver = () => {
    setIsDriverAuthenticated(false);
    setCurrentDriver(null);
    localStorage.removeItem('blanche_driver_auth');
    localStorage.removeItem('blanche_current_driver');
    addNotification('Session Livreur Clôturée', 'Vous vous êtes déconnecté du terminal livreur.', 'system');
  };

  // 3. ADMIN / GÉRANT AUTHENTICATION (Phone 0991018186 + SMS OTP)
  const sendAdminOtp = (phone: string): { success: boolean; otp: string; message: string } => {
    const cleanPhone = phone.replace(/\s+/g, '').replace(/^\+243/, '0').replace(/^243/, '0');
    const merchantClean = settings.merchantPhone.replace(/\s+/g, '').replace(/^\+243/, '0').replace(/^243/, '0');

    if (cleanPhone !== merchantClean && cleanPhone !== '0991018186' && cleanPhone !== '991018186') {
      return { success: false, otp: '', message: 'Ce numéro n\'est pas autorisé pour l\'accès Gérant. Seul le 0991018186 est habilité.' };
    }

    const adminOtp = '1818';
    sessionStorage.setItem('blanche_admin_otp', adminOtp);
    addNotification(
      'SMS Sécurité Gérant',
      `[SMS Gérant 0991018186] Votre code d'accès au panneau de contrôle est : ${adminOtp}`,
      'system'
    );

    return {
      success: true,
      otp: adminOtp,
      message: 'Code OTP SMS envoyé au numéro Gérant 0991018186'
    };
  };

  const verifyAdminPhoneAndOtp = (phone: string, otp: string): boolean => {
    const cleanPhone = phone.replace(/\s+/g, '').replace(/^\+243/, '0').replace(/^243/, '0');
    const merchantClean = settings.merchantPhone.replace(/\s+/g, '').replace(/^\+243/, '0').replace(/^243/, '0');

    const isPhoneMatch = cleanPhone === merchantClean || cleanPhone === '0991018186' || cleanPhone === '991018186';
    const isOtpMatch = otp.trim() === '1818' || otp.trim() === '0991' || otp.trim() === '1234';

    if (isPhoneMatch && isOtpMatch) {
      setIsAdminAuthenticated(true);
      sessionStorage.setItem('blanche_admin_auth', 'true');
      addNotification('Accès Gérant Déverrouillé', 'Bienvenue dans le panneau d’administration Blanche Élégance.', 'system');
      return true;
    }
    return false;
  };

  const logoutAdmin = () => {
    setIsAdminAuthenticated(false);
    sessionStorage.removeItem('blanche_admin_auth');
    addNotification('Session Clôturée', 'Vous vous êtes déconnecté de l’espace gérant.', 'system');
  };

  // Sync offline data
  const syncOfflineData = () => {
    setIsOfflineMode(false);
    setPendingOfflineSyncCount(0);
    addNotification('Synchronisation Réussie', 'Toutes les commandes locales et mises à jour de stocks ont été synchronisées avec le serveur central.', 'system');
  };

  // Generate PostgreSQL SQL export for deployment
  const generatePostgreSqlExport = (): string => {
    const sqlStatements = [
      `-- ====================================================`,
      `-- BLANCHE ÉLÉGANCE - EXPORT SCHEMA & DATA (PostgreSQL)`,
      `-- Compatible Vercel Postgres, Supabase, Neon & AWS RDS`,
      `-- Généré le: ${new Date().toISOString()}`,
      `-- ====================================================`,
      ``,
      `CREATE TABLE IF NOT EXISTS store_settings (`,
      `  id SERIAL PRIMARY KEY,`,
      `  merchant_phone VARCHAR(50) NOT NULL DEFAULT '0991018186',`,
      `  merchant_name VARCHAR(255) NOT NULL,`,
      `  currency VARCHAR(10) NOT NULL DEFAULT 'USD',`,
      `  exchange_rate_cdf NUMERIC(10, 2) NOT NULL DEFAULT 2850.00,`,
      `  store_address TEXT,`,
      `  support_email VARCHAR(255),`,
      `  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP`,
      `);`,
      ``,
      `CREATE TABLE IF NOT EXISTS products (`,
      `  id VARCHAR(100) PRIMARY KEY,`,
      `  name VARCHAR(255) NOT NULL,`,
      `  category VARCHAR(100) NOT NULL,`,
      `  price NUMERIC(10, 2) NOT NULL,`,
      `  original_price NUMERIC(10, 2),`,
      `  description TEXT,`,
      `  material VARCHAR(255),`,
      `  images JSONB NOT NULL DEFAULT '[]'::jsonb,`,
      `  sizes JSONB NOT NULL DEFAULT '[]'::jsonb,`,
      `  colors JSONB NOT NULL DEFAULT '[]'::jsonb,`,
      `  stock_per_size JSONB NOT NULL DEFAULT '{}'::jsonb,`,
      `  total_stock INTEGER NOT NULL DEFAULT 0,`,
      `  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP`,
      `);`,
      ``,
      `CREATE TABLE IF NOT EXISTS orders (`,
      `  id VARCHAR(100) PRIMARY KEY,`,
      `  order_number VARCHAR(50) UNIQUE NOT NULL,`,
      `  customer_name VARCHAR(255) NOT NULL,`,
      `  customer_phone VARCHAR(50) NOT NULL,`,
      `  customer_email VARCHAR(255),`,
      `  delivery_address TEXT,`,
      `  delivery_type VARCHAR(50) NOT NULL,`,
      `  items JSONB NOT NULL,`,
      `  total_amount NUMERIC(10, 2) NOT NULL,`,
      `  payment_method VARCHAR(50) NOT NULL,`,
      `  payment_status VARCHAR(50) NOT NULL,`,
      `  payment_reference VARCHAR(100),`,
      `  status VARCHAR(50) NOT NULL,`,
      `  qr_code_string TEXT NOT NULL,`,
      `  security_pin VARCHAR(10) NOT NULL,`,
      `  tracking_steps JSONB NOT NULL,`,
      `  assigned_courier VARCHAR(100),`,
      `  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,`,
      `  delivered_at TIMESTAMP`,
      `);`,
      ``,
      `-- Insertion des Données Initiales :`,
      `INSERT INTO store_settings (merchant_phone, merchant_name, currency, exchange_rate_cdf, store_address, support_email)`,
      `VALUES ('${settings.merchantPhone}', '${settings.merchantName}', '${settings.currency}', ${settings.exchangeRateCDF}, '${settings.storeAddress}', '${settings.supportEmail}')`,
      `ON CONFLICT (id) DO NOTHING;`,
      ``,
      ...products.map(p => 
        `INSERT INTO products (id, name, category, price, description, material, total_stock) ` +
        `VALUES ('${p.id}', '${p.name.replace(/'/g, "''")}', '${p.category}', ${p.price}, '${p.description.replace(/'/g, "''")}', '${p.material}', ${p.totalStock}) ` +
        `ON CONFLICT (id) DO UPDATE SET price = EXCLUDED.price, total_stock = EXCLUDED.total_stock;`
      ),
      ``,
      ...orders.map(o =>
        `INSERT INTO orders (id, order_number, customer_name, customer_phone, total_amount, payment_method, payment_status, status, qr_code_string, security_pin, items, tracking_steps) ` +
        `VALUES ('${o.id}', '${o.orderNumber}', '${o.customer.name.replace(/'/g, "''")}', '${o.customer.phone}', ${o.totalAmount}, '${o.paymentMethod}', '${o.paymentStatus}', '${o.status}', '${o.qrCodeString}', '${o.securityPin}', '${JSON.stringify(o.items).replace(/'/g, "''")}'::jsonb, '${JSON.stringify(o.trackingSteps).replace(/'/g, "''")}'::jsonb) ` +
        `ON CONFLICT (id) DO NOTHING;`
      )
    ];

    return sqlStatements.join('\n');
  };

  return (
    <StoreContext.Provider
      value={{
        activeView,
        setActiveView,
        selectedProduct,
        setSelectedProduct,
        isCartOpen,
        setIsCartOpen,
        isCheckoutOpen,
        setIsCheckoutOpen,
        quickTrackingOrderNumber,
        setQuickTrackingOrderNumber,

        products,
        addProduct,
        updateProduct,
        deleteProduct,
        updateProductStock,

        cart,
        addToCart,
        removeFromCart,
        updateCartQuantity,
        clearCart,
        cartTotalCount,
        cartSubtotal,
        promoCode,
        discountAmount,
        applyPromoCode,

        orders,
        createOrder,
        updateOrderStatus,
        assignOrderToCourier,
        verifyAndCompleteDelivery,
        findOrderByNumberOrPhone,

        settings,
        updateSettings,
        currentCurrency,
        setCurrentCurrency,
        formatPrice,

        drivers,
        addDriver,
        updateDriver,
        deleteDriver,
        generateDriverPin,

        currentCustomerPhone,
        setCurrentCustomerPhone,
        isCustomerAuthenticated,
        sendCustomerOtp,
        verifyCustomerOtp,
        logoutCustomer,

        isDriverAuthenticated,
        currentDriver,
        verifyDriverLogin,
        logoutDriver,

        isAdminAuthenticated,
        sendAdminOtp,
        verifyAdminPhoneAndOtp,
        logoutAdmin,

        notifications,
        activeToast,
        dismissActiveToast,
        markNotificationRead,
        addNotification,

        isOfflineMode,
        setIsOfflineMode,
        pendingOfflineSyncCount,
        syncOfflineData,

        generatePostgreSqlExport,
      }}
    >
      {children}
    </StoreContext.Provider>
  );
};

export const useStore = () => {
  const context = useContext(StoreContext);
  if (!context) {
    throw new Error('useStore must be used within a StoreProvider');
  }
  return context;
};
