export type ProductCategory = 
  | 'Robes & Soirée'
  | 'Tailleurs & Ensembles'
  | 'Chemisiers & Soie'
  | 'Manteaux & Vestes'
  | 'Pantalons & Jupes'
  | 'Chaussures & Maroquinerie'
  | 'Accessoires de Luxe';

export interface Product {
  id: string;
  name: string;
  category: ProductCategory;
  price: number;
  originalPrice?: number;
  description: string;
  details: string[];
  images: string[];
  sizes: string[];
  colors: { name: string; hex: string }[];
  stockPerSize: Record<string, number>;
  totalStock: number;
  isFeatured?: boolean;
  isNew?: boolean;
  material: string;
  rating: number;
  reviewCount: number;
  createdAt: string;
}

export interface CartItem {
  id: string; // unique cart item id: product.id + size + color
  product: Product;
  selectedSize: string;
  selectedColor: { name: string; hex: string };
  quantity: number;
}

export type PaymentMethodType = 'mpesa' | 'orange_money' | 'airtel_money' | 'card' | 'cash_delivery';

export type OrderStatus = 
  | 'pending_payment'
  | 'payment_confirmed'
  | 'in_preparation'
  | 'in_transit'
  | 'ready_for_pickup'
  | 'delivered'
  | 'cancelled';

export interface TrackingStep {
  id: string;
  status: OrderStatus;
  title: string;
  description: string;
  timestamp: string;
  location?: string;
  isCompleted: boolean;
  isCurrent: boolean;
}

export interface CustomerInfo {
  name: string;
  phone: string;
  email: string;
  address: string;
  city: string;
  notes?: string;
}

export interface Order {
  id: string;
  orderNumber: string;
  createdAt: string;
  updatedAt: string;
  customer: CustomerInfo;
  items: CartItem[];
  subtotal: number;
  shippingFee: number;
  discount: number;
  totalAmount: number;
  paymentMethod: PaymentMethodType;
  paymentStatus: 'pending' | 'verified' | 'failed';
  paymentReference?: string;
  deliveryType: 'delivery' | 'pickup';
  status: OrderStatus;
  qrCodeString: string;
  securityPin: string;
  trackingSteps: TrackingStep[];
  assignedCourierName?: string;
  courierPhone?: string;
  driverNotes?: string;
  deliverySignature?: string;
  deliveryPhotoProof?: string;
  deliveredAt?: string;
  offlineCreated?: boolean;
}

export interface PushNotification {
  id: string;
  title: string;
  message: string;
  type: 'order' | 'delivery' | 'stock' | 'payment' | 'system' | 'info';
  timestamp: string;
  orderId?: string;
  read: boolean;
}

export interface StoreSettings {
  merchantPhone: string; // Default: '0991018186'
  merchantName: string;
  currency: 'USD' | 'CDF' | 'EUR';
  exchangeRateCDF: number; // 1 USD = 2850 CDF approx
  exchangeRateEUR: number;
  freeShippingThreshold: number;
  standardShippingFee: number;
  expressShippingFee: number;
  storeAddress: string;
  storeCity: string;
  supportPhone: string;
  supportEmail: string;
}

export interface DeliveryDriver {
  id: string;
  name: string;
  phone: string;
  pinCode: string; // 4-digit PIN generated by Manager (Gérant)
  vehicle: string;
  zone: string;
  activeOrdersCount: number;
  rating: number;
  status: 'active' | 'offline' | 'on_break';
  createdAt?: string;
}
